package com.reverend.imagePreProcess.model;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectBatchId generated by hbm2java
 */
@Embeddable
public class ProjectBatchId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1360695366819715140L;
	private Long projectBatchesId;
	private Long batchId;

	public ProjectBatchId() {
	}

	public ProjectBatchId(Long projectBatchesId, Long batchId) {
		this.projectBatchesId = projectBatchesId;
		this.batchId = batchId;
	}

	@Column(name = "PROJECT_BATCHES_ID")
	public Long getProjectBatchesId() {
		return this.projectBatchesId;
	}

	public void setProjectBatchesId(Long projectBatchesId) {
		this.projectBatchesId = projectBatchesId;
	}

	@Column(name = "BATCH_ID")
	public Long getBatchId() {
		return this.batchId;
	}

	public void setBatchId(Long batchId) {
		this.batchId = batchId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProjectBatchId))
			return false;
		ProjectBatchId castOther = (ProjectBatchId) other;

		return ((this.getProjectBatchesId() == castOther.getProjectBatchesId()) || (this.getProjectBatchesId() != null && castOther.getProjectBatchesId() != null && this.getProjectBatchesId().equals(
				castOther.getProjectBatchesId())))
				&& ((this.getBatchId() == castOther.getBatchId()) || (this.getBatchId() != null && castOther.getBatchId() != null && this.getBatchId().equals(castOther.getBatchId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProjectBatchesId() == null ? 0 : this.getProjectBatchesId().hashCode());
		result = 37 * result + (getBatchId() == null ? 0 : this.getBatchId().hashCode());
		return result;
	}

}
